---
apiVersion: V1
kind: Pod
metadata:
  name: my-pod
  labels:
    app: my-app
spec:
  containers:
    -name: cbz-container
    image: httpd
    ports:
      -name: http
      containerPort: 80
      protocol: TCP
...